-- supabase/migrations/20260909_quote_builder.sql
--
-- ═══════════════════════════════════════════════════════════════════════
--  THE QUOTE ITSELF — prepared, edited, and sent from admin
-- ═══════════════════════════════════════════════════════════════════════
--
-- Runs AFTER 20260909_quote_requests.sql. Everything here is additive; the
-- table and its policies already exist.
--
-- Three things this adds.
--
-- 1. AN ACKNOWLEDGEMENT. Until now a prospect filled in the form, saw a green
--    confirmation, and then received nothing at all — while the on-screen
--    message promised them a written quote by email. ack_emailed_at records
--    that a receipt actually reached them, and ack_error records why it did
--    not, because "we sent it" is not a thing to take on trust.
--
-- 2. THE QUOTE. Prepared from the request, edited by Eric, then sent. Stored on
--    the same row rather than in a table of its own: a quote here belongs to
--    exactly one request and has no life without it.
--
-- 3. ⚠️ A GUARD ON THE PRICE. quote_total is generated by the database from
--    seats × unit price, not typed in and not sent up by the browser. A quote
--    whose line items and total disagree is worse than no quote — it is the one
--    document a buyer will hold you to. Making the total a computed column
--    means the two cannot drift, whatever the page sends.
--
-- Still no card, bank or routing numbers anywhere. How somebody wants to pay is
-- a word; what they pay with never enters this system.

BEGIN;

-- ── The acknowledgement they get straight away ───────────────────────
ALTER TABLE public.quote_requests
  ADD COLUMN IF NOT EXISTS ack_emailed_at timestamptz,
  ADD COLUMN IF NOT EXISTS ack_error      text;

COMMENT ON COLUMN public.quote_requests.ack_emailed_at IS
  'When the automatic receipt reached the prospect. Null with ack_error set means it did not, and the pricing page had already promised them an email.';

-- ── The quote ────────────────────────────────────────────────────────
ALTER TABLE public.quote_requests
  -- Human-facing reference. A public buyer puts this on a purchase order, so
  -- it has to be stable once issued and unique across everything ever sent.
  ADD COLUMN IF NOT EXISTS quote_no          text,
  ADD COLUMN IF NOT EXISTS quote_prepared_at timestamptz,

  -- The line items, all editable. Defaults match the published Team offer;
  -- above six seats the page deliberately leaves them empty rather than
  -- prefilling a price the rate card does not cover.
  ADD COLUMN IF NOT EXISTS quote_seats       integer  CHECK (quote_seats IS NULL OR (quote_seats > 0 AND quote_seats <= 5000)),
  ADD COLUMN IF NOT EXISTS quote_unit_price  numeric(10,2) CHECK (quote_unit_price IS NULL OR quote_unit_price >= 0),
  ADD COLUMN IF NOT EXISTS quote_free_seats  integer  CHECK (quote_free_seats IS NULL OR quote_free_seats >= 0),

  ADD COLUMN IF NOT EXISTS quote_valid_until date,
  ADD COLUMN IF NOT EXISTS quote_intro       text,
  ADD COLUMN IF NOT EXISTS quote_terms       text,

  ADD COLUMN IF NOT EXISTS quote_sent_at     timestamptz,
  ADD COLUMN IF NOT EXISTS quote_send_error  text,
  ADD COLUMN IF NOT EXISTS quote_sent_to     text;

-- ⚠️ The total is DERIVED. It cannot be set, so it cannot disagree with the
-- line items above it. If the browser sends a total, it is ignored.
ALTER TABLE public.quote_requests
  DROP COLUMN IF EXISTS quote_total;
ALTER TABLE public.quote_requests
  ADD COLUMN quote_total numeric(12,2)
  GENERATED ALWAYS AS (round(coalesce(quote_seats,0) * coalesce(quote_unit_price,0), 2)) STORED;

COMMENT ON COLUMN public.quote_requests.quote_total IS
  'Computed from quote_seats * quote_unit_price. Never written directly - a quote whose total disagrees with its line items is the one document a buyer will hold you to. Free seats are additional and by definition add nothing.';

-- A quote number, once issued, must not be reused. Partial so that the many
-- requests with no quote yet do not collide on null.
CREATE UNIQUE INDEX IF NOT EXISTS quote_requests_quote_no_idx
  ON public.quote_requests (quote_no) WHERE quote_no IS NOT NULL;

-- ── Sending a quote moves the request along by itself ────────────────
-- Otherwise the status is a second thing to remember, and the one that gets
-- forgotten is the one that makes the list untrustworthy.
CREATE OR REPLACE FUNCTION public.quote_sent_advances_status()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.quote_sent_at IS NOT NULL
     AND (OLD.quote_sent_at IS NULL)
     AND NEW.status IN ('new','contacted') THEN
    NEW.status := 'quoted';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS quote_sent_advances_status_trg ON public.quote_requests;
CREATE TRIGGER quote_sent_advances_status_trg
  BEFORE UPDATE OF quote_sent_at ON public.quote_requests
  FOR EACH ROW EXECUTE FUNCTION public.quote_sent_advances_status();

-- ── Deleting ─────────────────────────────────────────────────────────
-- Eric asked to be able to remove a request that is fake or unwanted. DELETE is
-- already granted to authenticated and gated to admins by quote_requests_admin
-- from the first migration, so there is nothing to add here — but it is worth
-- writing down that 'spam' exists as a status precisely so that hiding a
-- request and destroying it stay separate decisions. A deleted row is gone;
-- there is no undo, and the admin page asks twice for that reason.

COMMIT;
