-- supabase/migrations/20260908_outreach_states.sql
-- State tags, for the 342 organisations whose state the domain proves.
--
-- Only three rules are used, because a looser one lied confidently: taking the
-- last two letters of any label tagged gnoinc.org (New Orleans) as NC,
-- opportunityaustin.com (Texas) as IN, maricopa.gov (Arizona) as PA and
-- gmail.com as IL. A wrong state is worse than a missing one, because a
-- 'Texas EDCs' segment still returns rows and nothing looks broken.
--
--   .us domains       the label before 'us' IS the state - co.ontario.ny.us
--                     is Ontario County, NEW YORK, not Colorado
--   a full state name as its own label   beaver.utah.gov, michigan.org
--   a full state name ending the label   longviewtexas.gov, conwayarkansas.org
--
-- The remaining 2505 organisations get their state from research, off the
-- website itself, which is the only source that actually knows.
BEGIN;

INSERT INTO public.outreach_tags (slug,label,kind,colour,description) VALUES
  ('state-ak','AK','derived','slate','Organisation is in AK.'),
  ('state-al','AL','derived','slate','Organisation is in AL.'),
  ('state-ar','AR','derived','slate','Organisation is in AR.'),
  ('state-ca','CA','derived','slate','Organisation is in CA.'),
  ('state-co','CO','derived','slate','Organisation is in CO.'),
  ('state-de','DE','derived','slate','Organisation is in DE.'),
  ('state-fl','FL','derived','slate','Organisation is in FL.'),
  ('state-ga','GA','derived','slate','Organisation is in GA.'),
  ('state-hi','HI','derived','slate','Organisation is in HI.'),
  ('state-ia','IA','derived','slate','Organisation is in IA.'),
  ('state-id','ID','derived','slate','Organisation is in ID.'),
  ('state-il','IL','derived','slate','Organisation is in IL.'),
  ('state-in','IN','derived','slate','Organisation is in IN.'),
  ('state-ks','KS','derived','slate','Organisation is in KS.'),
  ('state-ma','MA','derived','slate','Organisation is in MA.'),
  ('state-md','MD','derived','slate','Organisation is in MD.'),
  ('state-me','ME','derived','slate','Organisation is in ME.'),
  ('state-mi','MI','derived','slate','Organisation is in MI.'),
  ('state-mn','MN','derived','slate','Organisation is in MN.'),
  ('state-mo','MO','derived','slate','Organisation is in MO.'),
  ('state-ms','MS','derived','slate','Organisation is in MS.'),
  ('state-mt','MT','derived','slate','Organisation is in MT.'),
  ('state-nc','NC','derived','slate','Organisation is in NC.'),
  ('state-nd','ND','derived','slate','Organisation is in ND.'),
  ('state-ne','NE','derived','slate','Organisation is in NE.'),
  ('state-nj','NJ','derived','slate','Organisation is in NJ.'),
  ('state-nm','NM','derived','slate','Organisation is in NM.'),
  ('state-nv','NV','derived','slate','Organisation is in NV.'),
  ('state-ny','NY','derived','slate','Organisation is in NY.'),
  ('state-oh','OH','derived','slate','Organisation is in OH.'),
  ('state-or','OR','derived','slate','Organisation is in OR.'),
  ('state-pa','PA','derived','slate','Organisation is in PA.'),
  ('state-sd','SD','derived','slate','Organisation is in SD.'),
  ('state-tn','TN','derived','slate','Organisation is in TN.'),
  ('state-tx','TX','derived','slate','Organisation is in TX.'),
  ('state-ut','UT','derived','slate','Organisation is in UT.'),
  ('state-va','VA','derived','slate','Organisation is in VA.'),
  ('state-vt','VT','derived','slate','Organisation is in VT.'),
  ('state-wa','WA','derived','slate','Organisation is in WA.'),
  ('state-wi','WI','derived','slate','Organisation is in WI.'),
  ('state-wy','WY','derived','slate','Organisation is in WY.')
ON CONFLICT (slug) DO NOTHING;

UPDATE public.outreach_orgs o SET state = v.st FROM (VALUES
  ('co.ontario.ny.us','NY'),
  ('state.nm.us','NM'),
  ('co.camden.ga.us','GA'),
  ('ci.southlake.tx.us','TX'),
  ('dublin.oh.us','OH'),
  ('jobsohio.com','OH'),
  ('palmbayflorida.org','FL'),
  ('nassauflorida.com','FL'),
  ('longviewtexas.gov','TX'),
  ('muscatineiowa.gov','IA'),
  ('georgia.org','GA'),
  ('michigan.org','MI'),
  ('co.jasper.ms.us','MS'),
  ('robinsontexas.org','TX'),
  ('ci.smithville.tx.us','TX'),
  ('grahamtexas.net','TX'),
  ('enterpriseflorida.com','FL'),
  ('grand-rapids.mi.us','MI'),
  ('co.augusta.va.us','VA'),
  ('ci.kent.wa.us','WA'),
  ('austintexas.gov','TX'),
  ('clutetexas.gov','TX'),
  ('clevelandtexas.com','TX'),
  ('beaumonttexas.gov','TX'),
  ('morgancountyutah.gov','UT'),
  ('ottawakansas.org','KS'),
  ('fcedc-ohio.com','OH'),
  ('upstatecolorado.org','CO'),
  ('co.owyhee.id.us','ID'),
  ('co.sabine.tx.us','TX'),
  ('fulsheartexas.gov','TX'),
  ('maryland.gov','MD'),
  ('co.cass.in.us','IN'),
  ('co.middlesex.nj.us','NJ'),
  ('ci.stpaul.mn.us','MN'),
  ('investnebraska.com','NE'),
  ('wylietexas.gov','TX'),
  ('fcdckansas.org','KS'),
  ('ci.lancaster.oh.us','OH'),
  ('oconee.ga.us','GA'),
  ('mansfieldtexas.gov','TX'),
  ('beecounty.texas.gov','TX'),
  ('conwayarkansas.org','AR'),
  ('dobusinessinmontana.com','MT'),
  ('eastman-georgia.com','GA'),
  ('vandaliaillinois.com','IL'),
  ('co.benton.wa.us','WA'),
  ('ci.snyder.tx.us','TX'),
  ('ci.red-wing.mn.us','MN'),
  ('breckenridgetexas.com','TX'),
  ('crane.texas.gov','TX'),
  ('mcohio.org','OH'),
  ('bcutah.gov','UT'),
  ('ohio.edu','OH'),
  ('r6.utah.gov','UT'),
  ('co.kent.de.us','DE'),
  ('starkcoohio.com','OH'),
  ('ci.pendleton.or.us','OR'),
  ('geneva.il.us','IL'),
  ('co.cameron.tx.us','TX'),
  ('lagovistatexas.gov','TX'),
  ('fairviewtexas.org','TX'),
  ('brewermaine.gov','ME'),
  ('co.warren.oh.us','OH'),
  ('desototexas.gov','TX'),
  ('auburnmaine.gov','ME'),
  ('madisonmaine.com','ME'),
  ('uptexas.org','TX'),
  ('co.lancaster.pa.us','PA'),
  ('carrollcountyohio.us','OH'),
  ('seguintexas.gov','TX'),
  ('co.ozaukee.wi.us','WI'),
  ('ci.sealy.tx.us','TX'),
  ('dickinsontexas.gov','TX'),
  ('levellandtexas.org','TX'),
  ('co.robertson.tx.us','TX'),
  ('ci.crowley.tx.us','TX'),
  ('midlandtexas.gov','TX'),
  ('clydeohio.org','OH'),
  ('fountaincolorado.org','CO'),
  ('ci.veneta.or.us','OR'),
  ('town.northlake.tx.us','TX'),
  ('clarksville.tn.us','TN'),
  ('wheelertexas.org','TX'),
  ('mississippi.org','MS'),
  ('candowyoming.com','WY'),
  ('atlantatexas.org','TX'),
  ('tylertexas.com','TX'),
  ('opportunityflorida.com','FL'),
  ('gonzales.texas.gov','TX'),
  ('urbanaillinois.us','IL'),
  ('milwaukieoregon.gov','OR'),
  ('blackfordindiana.com','IN'),
  ('commerce.alabama.gov','AL'),
  ('neindiana.com','IN'),
  ('sweetwatertexas.net','TX'),
  ('ci.laredo.tx.us','TX'),
  ('co.armstrong.pa.us','PA'),
  ('carthagetexas.com','TX'),
  ('co.butler.pa.us','PA'),
  ('friscotexas.gov','TX'),
  ('montana.edu','MT'),
  ('southernidaho.org','ID'),
  ('co.sherman.tx.us','TX'),
  ('co.charles-city.va.us','VA'),
  ('loganutah.org','UT'),
  ('mexicomissouri.org','MO'),
  ('greshamoregon.gov','OR'),
  ('co.jones.tx.us','TX'),
  ('clintonillinois.com','IL'),
  ('co.robeson.nc.us','NC'),
  ('grapevinetexas.gov','TX'),
  ('co.chautauqua.ny.us','NY'),
  ('sjc.utah.gov','UT'),
  ('choosedelaware.com','DE'),
  ('discoverclaytonnewmexico.org','NM'),
  ('portsofindiana.com','IN'),
  ('zion.il.us','IL'),
  ('alaska.gov','AK'),
  ('clarkcountyohio.gov','OH'),
  ('co.schuylkill.pa.us','PA'),
  ('annatexas.gov','TX'),
  ('ci.waynesboro.va.us','VA'),
  ('evanscolorado.gov','CO'),
  ('sintontexas.org','TX'),
  ('commerce.idaho.gov','ID'),
  ('clarkecountyiowa.com','IA'),
  ('nnpdc17.state.va.us','VA'),
  ('bellevuenebraska.com','NE'),
  ('camerontexas.net','TX'),
  ('uintah.utah.gov','UT'),
  ('woodwaytexas.gov','TX'),
  ('co.lawrence.ms.us','MS'),
  ('georgetowntexas.gov','TX'),
  ('state.co.us','CO'),
  ('co.middlesex.va.us','VA'),
  ('goodingidaho.org','ID'),
  ('provo.utah.gov','UT'),
  ('woodbury.nj.us','NJ'),
  ('cepohio.com','OH'),
  ('co.westmoreland.pa.us','PA'),
  ('marionarkansas.org','AR'),
  ('hot.cog.tx.us','TX'),
  ('windhammaine.us','ME'),
  ('georgetownohio.gov','OH'),
  ('mansfield-texas.com','TX'),
  ('knoxcountyindiana.com','IN'),
  ('cockrell-hill.tx.us','TX'),
  ('vermont.gov','VT'),
  ('newportoregon.gov','OR'),
  ('ci.port-neches.tx.us','TX'),
  ('co.clatsop.or.us','OR'),
  ('cantonohio.gov','OH'),
  ('seymourmissouri.org','MO'),
  ('utexas.edu','TX'),
  ('franklincountyohio.gov','OH'),
  ('tooltexas.org','TX'),
  ('city.cleveland.oh.us','OH'),
  ('centervilleohio.gov','OH'),
  ('sherwoodoregon.gov','OR'),
  ('ci.benicia.ca.us','CA'),
  ('leonvalleytexas.gov','TX'),
  ('huntley.il.us','IL'),
  ('co.clarion.pa.us','PA'),
  ('co.cass.mn.us','MN'),
  ('fortworthtexas.gov','TX'),
  ('mcgregor-texas.com','TX'),
  ('centralmaine.org','ME'),
  ('bolivar.mo.us','MO'),
  ('hamilton-ohio.com','OH'),
  ('co.bailey.tx.us','TX'),
  ('ci.international-falls.mn.us','MN'),
  ('prattkansas.org','KS'),
  ('ci.moscow.id.us','ID'),
  ('killeentexas.gov','TX'),
  ('intersectillinois.org','IL'),
  ('nebraska.gov','NE'),
  ('irp.idaho.gov','ID'),
  ('co.ocean.nj.us','NJ'),
  ('cochawaii.org','HI'),
  ('newbergoregon.gov','OR'),
  ('gov.texas.gov','TX'),
  ('hooveralabama.gov','AL'),
  ('ci.boerne.tx.us','TX'),
  ('garfield.utah.gov','UT'),
  ('elgintexas.gov','TX'),
  ('cedarparktexas.gov','TX'),
  ('ceo.co.indiana.pa.us','PA'),
  ('washco.utah.gov','UT'),
  ('cityofcanadiantexas.com','TX'),
  ('biloxi.ms.us','MS'),
  ('beltontexas.gov','TX'),
  ('merkeltexas.com','TX'),
  ('soutah.org','UT'),
  ('delawareohio.net','OH'),
  ('noblesville.in.us','IN'),
  ('ketchumidaho.org','ID'),
  ('ci.alamosa.co.us','CO'),
  ('weimartexas.org','TX'),
  ('ci.greenville.tx.us','TX'),
  ('whitesborotexas.com','TX'),
  ('obetz.oh.us','OH'),
  ('careersourceflorida.com','FL'),
  ('ci.wilsonville.or.us','OR'),
  ('co.delaware.oh.us','OH'),
  ('co.valley.id.us','ID'),
  ('co.fayette.tx.us','TX'),
  ('vermont.org','VT'),
  ('brownwoodtexas.gov','TX'),
  ('state.mn.us','MN'),
  ('huroncountyohio.com','OH'),
  ('selectparistexas.com','TX'),
  ('ci.mansfield.oh.us','OH'),
  ('mckinneytexas.org','TX'),
  ('biz.oregon.gov','OR'),
  ('oer.idaho.gov','ID'),
  ('rawlins-wyoming.com','WY'),
  ('ci.richland.wa.us','WA'),
  ('ci.newark.nj.us','NJ'),
  ('lebanonoregon.gov','OR'),
  ('ciscotexas.gov','TX'),
  ('roanoketexas.com','TX'),
  ('missiontexas.us','TX'),
  ('daytonohio.gov','OH'),
  ('elpasotexas.gov','TX'),
  ('ci.selma.tx.us','TX'),
  ('portlandmaine.gov','ME'),
  ('clermontcountyohio.gov','OH'),
  ('springfield.il.us','IL'),
  ('co.polk.or.us','OR'),
  ('beavertonoregon.gov','OR'),
  ('lemont.il.us','IL'),
  ('co.rockingham.nc.us','NC'),
  ('wtcutah.com','UT'),
  ('health.missouri.edu','MO'),
  ('ci.goldendale.wa.us','WA'),
  ('lucastexas.us','TX'),
  ('ci.montgomery.tx.us','TX'),
  ('rupert.id.us','ID'),
  ('lasvegasnevada.gov','NV'),
  ('selectflorida.org','FL'),
  ('ci.corsicana.tx.us','TX'),
  ('businessintexas.com','TX'),
  ('holliston.k12.ma.us','MA'),
  ('sudbury.ma.us','MA'),
  ('ferristexas.gov','TX'),
  ('morgancountyohio.gov','OH'),
  ('co.bergen.nj.us','NJ'),
  ('essex-virginia.org','VA'),
  ('co.hernando.fl.us','FL'),
  ('co.hidalgo.tx.us','TX'),
  ('eastlandtexas.gov','TX'),
  ('ranchoviejotexas.com','TX'),
  ('sandpointidaho.gov','ID'),
  ('parkertexas.us','TX'),
  ('hilliardohio.gov','OH'),
  ('centralvirginia.org','VA'),
  ('simontontexas.gov','TX'),
  ('ci.xenia.oh.us','OH'),
  ('co.ulster.ny.us','NY'),
  ('co.rock.wi.us','WI'),
  ('orangetexas.gov','TX'),
  ('centertexas.org','TX'),
  ('newtontexas.org','TX'),
  ('beaver.utah.gov','UT'),
  ('ontariooregon.org','OR'),
  ('alturaidaho.com','ID'),
  ('atchisonkansas.net','KS'),
  ('grantspassoregon.gov','OR'),
  ('magutah.gov','UT'),
  ('hudson.oh.us','OH'),
  ('emery.utah.gov','UT'),
  ('carbon.utah.gov','UT'),
  ('brunswick.oh.us','OH'),
  ('columbustexas.net','TX'),
  ('diberville.ms.us','MS'),
  ('corvallisoregon.gov','OR'),
  ('co.humboldt.ca.us','CA'),
  ('aurora.il.us','IL'),
  ('choose-texas.com','TX'),
  ('prairieviewtexas.gov','TX'),
  ('brag.utah.gov','UT'),
  ('co.kemper.ms.us','MS'),
  ('childresstexas.net','TX'),
  ('co.gooding.id.us','ID'),
  ('spotsylvania.va.us','VA'),
  ('seualg.utah.gov','UT'),
  ('maine.gov','ME'),
  ('harrisoncountyohio.org','OH'),
  ('ci.madisonville.tx.us','TX'),
  ('gorham.me.us','ME'),
  ('ci.charlotte.nc.us','NC'),
  ('ottumwaiowa.com','IA'),
  ('marshalltexas.net','TX'),
  ('ci.lumberton.nc.us','NC'),
  ('medcoiowa.org','IA'),
  ('westcentraltexas.org','TX'),
  ('poteettexas.gov','TX'),
  ('terrelltexas.com','TX'),
  ('unionmissouri.gov','MO'),
  ('aptalaska.net','AK'),
  ('paristexas.gov','TX'),
  ('wrightco.iowa.gov','IA'),
  ('co.ellis.tx.us','TX'),
  ('centralcalifornia.org','CA'),
  ('canbyoregon.gov','OR'),
  ('lebanonohio.gov','OH'),
  ('illinois.gov','IL'),
  ('niederwald.texas.gov','TX'),
  ('ci.independence.or.us','OR'),
  ('mcminnvilleoregon.gov','OR'),
  ('co.cape-may.nj.us','NJ'),
  ('sangertexas.org','TX'),
  ('starbase.texas.gov','TX'),
  ('webercountyutah.gov','UT'),
  ('duchesne.utah.gov','UT'),
  ('co.hunterdon.nj.us','NJ'),
  ('co.yamhill.or.us','OR'),
  ('ci.staunton.va.us','VA'),
  ('hanovervirginia.com','VA'),
  ('ci.rosemount.mn.us','MN'),
  ('chesterfield.mo.us','MO'),
  ('maine.edu','ME'),
  ('ci.williston.nd.us','ND'),
  ('willoughbyohio.com','OH'),
  ('roundrocktexas.gov','TX'),
  ('bellevueidaho.us','ID'),
  ('co.grand.co.us','CO'),
  ('portofmontana.org','MT'),
  ('auburnalabama.org','AL'),
  ('carrollcountyohio.com','OH'),
  ('ci.monmouth.or.us','OR'),
  ('portlandoregon.gov','OR'),
  ('city.jackson.ms.us','MS'),
  ('state.sd.us','SD'),
  ('co.gibson.tn.us','TN'),
  ('bangormaine.gov','ME'),
  ('co.kings.ca.us','CA'),
  ('hillsboro-oregon.gov','OR'),
  ('bullardtexas.net','TX'),
  ('newalbanyohio.org','OH'),
  ('co.bastrop.tx.us','TX')
) AS v(domain,st) WHERE o.domain = v.domain;

INSERT INTO public.outreach_org_tags (domain, tag, added_by)
SELECT domain, 'state-'||lower(state), 'system' FROM public.outreach_orgs
 WHERE state IS NOT NULL ON CONFLICT DO NOTHING;

COMMIT;

SELECT state, count(*) AS organisations FROM public.outreach_orgs
 WHERE state IS NOT NULL GROUP BY state ORDER BY count(*) DESC LIMIT 12;